### ISSUE TITLE
Update Roda when new release lands

### ISSUE THREAD

**Issue by jgarber623** [jgarber623/indieweb-endpoints.cc#208]
## To-Do

- [x] remove `github:` source from `gem 'roda'` in `Gemfile`
- [x] rerun `bundle install`
- [x] remove `git` from list of packages installed in `Dockerfile` during "Production Build Stage"
